### PR TITLE
Working on making boost not required if we happen to have a C++17 compiler

### PR DESCRIPTION
**Pull request by eteran**
Working on making boost not required if we happen to have a C++17 compiler

Abstracts all boost usage to a new `Ext` library that will be std if we have C++17, or boost otherwise.

### CODE REVIEW

**Comment by grege2** [comment]
Hi @eteran Thanks for the great work on nedit-ng. I using it very successfully every day on Mac. I've been wondering for ages what Boost actually does for the app. Is it performance improvements, convenience, some of both ? This is a pretty lazy question, I should look at Boost product page, and your library of abstracted usage. I'll try to rebuild my nedit-ng on Big Sur 11.6.4 soon. Cheers.

**Comment by eteran** [comment]
Good question. So boost is a large set of c++ libraries that often acts as a sort of staging ground for future standard library features to come.

So right now, NG uses boost specifically for 2 things.

1. An implementation of optional, which is a value type that have "no value". Very handy in avoiding unnecessary heap allocations when you want to return something or nothing.

2. An implementation of variant, which is kind of a "discriminated union" type. That is it's a single variable that can be one of several compile time decided types. But also supports objects with constructors and will properly call destructors when appropriate because it tracks the type being held.

Both of these exist in c++17, and are available in earlier standards via boost.

**Comment by eteran** [comment]
Note, I deleted this PR not because I don't plan to pursue it. But because this PR didn't quite have the implementation as clean as I would have liked and it's relatively low priority.

I will eventually resume that effort.

**Comment by grege2** [comment]
I had a quick look at some Boost doco:

https://www.boost.org/doc/libs/1_78_0/libs/optional/doc/html/boost_optional/tutorial/when_to_use_optional.html

https://www.boost.org/doc/libs/1_78_0/doc/html/variant.html

My C++ is too out of date to get much from it, but looks interesting.

**Pull request closed without merging**
