### PR TITLE
initial translation for fi

### PR DESCRIPTION
**Pull request by marilmanen**
I had issues with some dialog buttons, but this should be ok as an initial translation to Finnish

### CODE REVIEW

**Comment by eteran** [comment]
Oh hell yes!

Thanks!

**Comment by marilmanen** [comment]
I thought that Finnish and French translations would work in the same way, but I can get only the French translation with these commands

env LANGUAGE=fr nedit-ng
env LANGUAGE=fi nedit-ng

I have tried also changing my desktop primary language to Finnish and all other programs are showing the Finnish transalations, so it does not look like an issue with my setup....

**Comment by eteran** [comment]
Hmm, it SHOULD work the same way. It's been a bit since this was merged, but I'll check to make sure that everything is in there correctly. It's probably something small.

**Comment by eteran** [comment]
Ahh, looking at this commit, it looks like the TS file just needs to be added to the build rules and then it should "just work". I'll try to get a patch in ASAP.

**Comment by eteran** [comment]
Should be fixed in master now!

**Pull request merged**
