### PR TITLE
Implementing the last few macro functions from NEdit classic :-) 

### PR DESCRIPTION
**Pull request by eteran**
* Implementing `toggle_overstrike` and `process_home` despite not being mentioned in the original NEdit documentation.

More of these lingering macro implementations to come!

### CODE REVIEW

**Comment by tksoh** [comment]
If this is going take awhile, can you rebase/merge-in the bookmark update? So I can test using my tagstack macros.

**Comment by eteran** [comment]
@tksoh sorry, I didn't see your comment. Yea, I'll pull the latest master into this so it has the latest fixes.

**Comment by tksoh** [comment]
@eteran No problem. I figured you must be really busy. Actually I've been operating the tagstack macros with a workaround - using open() to raise the window, instead of raise_window().

**Comment by eteran** [comment]
Made out of date by recent commits. Not all macros are implemented, but several more are!

**Pull request closed without merging**
